
- name: Include master Reality Keys setup
  include_tasks: "tasks/setup-reality-keys/setup-reality-keys-master.yml"
  when: "'master' in group_names"

- name: Include node Reality Keys setup
  include_tasks: "tasks/setup-reality-keys/setup-reality-keys-node.yml"
  when: "'nodes' in group_names"
