---
image_name: "ghcr.io/anton7p/cloud-node"
image_tag: "latest"
domain_name: "balalaika-vpn.duckdns.org"
db_password: "Antoha_7p"
redis_password: "Antoha_7p"
telegram_bot_token: "8584767448:AAHikPt3IZ6BWy36VheD_SnrQFQ_t-NEb8k"
encryption_key: "eeea0dea3f4e2eadc64884788a09fd1a74d391114554a3c56b0edf0c7904d24d"
vpn_admin_username: "mario"
vpn_admin_password: "Antoha_7p"
infrastructure_ip_list: '[{"address":"109.172.95.82","password":"COFoU41dPF63"}]'
github_actor: "Anton7p"
github_token: "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"
reality_public_key: ""
reality_short_id: ""
