
[nodes]
; Infrastructure nodes (Marzban Nodes)
109.172.95.82 


[nodes:vars]
ansible_user=root
ansible_ssh_pass=COFoU41dPF63
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_extra_args=-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null

