; Ansible inventory for LOCAL TESTING ONLY
; DO NOT commit this file - use inventory.ini.example for template

[master]
62.60.229.227

[master:vars]
ansible_user=root
ansible_ssh_pass=l1r0jS0FR5xT
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args=-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o PubkeyAuthentication=no

[nodes]
; Infrastructure nodes (Marzban Nodes)
; 213.108.23.243 ansible_user=root ansible_ssh_pass=tvifj5Z3GG8s

[nodes:vars]
ansible_user=root
ansible_ssh_private_key_file=~/.ssh/id_ed25519
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_extra_args=-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
