---
# Master Deployment Entry Point
# This file orchestrates all master-specific deployment tasks
# ==========================================

- name: Include authentication tasks
  include_tasks: "tasks/marzban/master/authentication.yml"

- name: Include key generation tasks
  include_tasks: "tasks/marzban/master/keys-generation.yml"

# NOTE: Inbound is NOT created on master - Xray runs on nodes only
# Master only hosts the Marzban panel

- name: Include bot environment tasks
  include_tasks: "tasks/marzban/master/bot-env.yml"
