// ============================================================================
// ЭМОДЗИ (минимальный набор для clean UI + legacy для совместимости)
// ============================================================================

export const EMOJI = {
  // Clean UI Icons (used)
  APPLE: '🍎',
  ANDROID: '🤖',
  WINDOWS: '💻',
  MACOS: '🖥️',
  COPY: '📋',
  ACTIVE: '✅',
  BACK: '🔙',
  PHONE: '📱',

  // Legacy icons (for backward compatibility)
  CORE: '💠',
  SQUARE: '🟦',
  BOLT: '⚡️',
  BATTERY: '🔋',
  SHIELD: '🛡',
  TERMINAL: '📟',
  LOCK: '🔒',
  UNLOCK: '🔓',
  WAVE: '👋',
  SERVER: '🖥️',
  LOCATION: '🌍',
  ROCKET: '🚀',
  PROFILE: '👤',
  INSTRUCTIONS: '📖',
  REFERRAL: '👥',
  HELP: '❓',
  PREMIUM: '💎',
  FREE: '🆓',
  INACTIVE: '❌',
  ID: '🆔',
  SUBSCRIPTION: '📅',
  TIME: '⏱️',
  TRAFFIC: '📊',
  KEY: '🔑',
  EXTEND: '💎',
  MONEY: '💰',
  LINK: '🔗',
  CHART: '📊',
  CARD: '💳',
  CHECK: '✅',
  NO: '❌',
  ANTENNA: '📡',
  ARROW_RIGHT: '➡️',
  BULLET: '•',
  ONE: '1️⃣',
  TWO: '2️⃣',
  THREE: '3️⃣',
  BULB: '💡',
  CROSS: '✖️',
  PERCENT: '%',
} as const;
